version: '0.2'
services:
  backend:
    container_name: backend
    build: ./backend
    environment:
      HTTP_PORT: 8080
    env_file:
      - path: ./infrastructure/postgre/postgres.env
        required: true
    ports:
      - 8080:8080
    depends_on:
      - database
      - mqtt
    networks:
      - swt-network
  
  fake_service:
    container_name: fake_service
    build: ./fake_service
    environment:
      HTTP_PORT: 8080
    env_file:
      - path: ./infrastructure/postgre/postgres.env
        required: true
    depends_on: 
      - database#
      - mqtt
    networks:
      - swt-network
  
  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  database:
    image: postgres:17
    container_name: database
    restart: always
    env_file: 
      - path: ./infrastructure/postgre/postgres.env
        required: true
    volumes:
      - ./infrastructure/postgre/data:/var/lib/postgresql/data
#    ports:
#      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - swt-network

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./infrastructure/mosquitto/config:/mosquitto/config
      - ./infrastructure/mosquitto/data:/mosquitto/data
      - ./infrastructure/mosquitto/log:/mosquitto/log
    networks:
      - swt-network


networks:
  swt-network:
    name: swt-network
    driver: bridge
