version: '0.1'
services:
  backend:
    image: swt/backendcontainer
    environment:
      HTTP_PORT: 8080
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file: "infrastructure/postgres.env"
