
services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - path: ./infrastructure/postgres.env
        required: true
      - path: ./infrstructure/mosquitto.env
        required: true
      - path: ./infrstructure/backend.env
        required: true
    depends_on:
      - database
      - mqtt
    networks:
      - swt-network
  
  fake_service:
    container_name: fake_service
    build: ./fake_service
    env_file:
      - path: ./infrastructure/postgres.env
        required: true
      - path: ./infrstructure/mosquitto.env
        required: true
      - path: ./infrstructure/fake_service.env
        required: true
    depends_on: 
      - database
      - mqtt
    networks:
      - swt-network
  
  frontend:
    container_name: frontend
    build: 
      context: frontend
      args:
        BACKEND_HOST: ${BACKEND_HOST}
        BACKEND_PORT: ${HTTP_PORT}
    env_file:
      - path: ./infrastucture/fontend.env
        required: true
      - path: ./infrstructure/backend.env
        required: true
    ports:
      - 5173:3000

  database:
    image: postgres:17
    container_name: database
    restart: always
    env_file: 
      - path: ./infrastructure/postgres.env
        required: true
    volumes:
      - ./infrastructure/postgre/data:/var/lib/postgresql/data
    networks:
      - swt-network

  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    volumes:
      - ./infrastructure/mosquitto/config:/mosquitto/config
      - ./infrastructure/mosquitto/data:/mosquitto/data
      - ./infrastructure/mosquitto/log:/mosquitto/log
    networks:
      - swt-network


networks:
  default:
    name: swt-network
    driver: bridge
