version: '0.2'
services:
  backend:
    image: swt/backendcontainer
    environment:
      HTTP_PORT: 8080
    env_file:
      - path: ./infrastructure/postgres.env
        required: true
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db
  
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file: 
      - path: ./infrastructure/postgres.env
        required: true
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
